### ISSUE TITLE
Compilation issues with nodejs perhaps should be mentioned in README.md

### ISSUE THREAD

**Issue by joha2** [paulfitz/cosmicos#9]
I tried to compile your project shortly ago and had difficulties doing that under

`Linux 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

I solved the compiling issues by performing a symlink from nodejs to node in the /usr/bin
directory

`lrwxrwxrwx 1 root root      15 Jun 17 19:05 /usr/bin/node -> /usr/bin/nodejs`

Maybe this could be mentioned in the README file.

Best wishes
Johannes

**Comment by aw1231** [comment]
AFAIK, this is common practice (google: node nodejs symlink).  However, because I don't have that much experience in this, it may still be useful for those who come along later to have that as a tip.  So, yes, I agree, it would be a good idea to add to the README.  Regarding the questions you added to the wiki, those questions seem to be a good start at a FAQ so I'll leave them there.  I'll hopefully work on filling out those, but as I am not the creator, I may not be able to give the best answers.

**Comment by paulfitz** [comment]
Adding to README makes sense to me too. @aw1231 if you have time for this that would be wonderful.

**Comment by aw1231** [comment]
See #10.  Check the wording though.

**Comment by joha2** [comment]
Thank you for your immediate answers :-) To make the compilation error more explicit I removed the symlink again. This is the resulting output:

    [  9%] Generating COS_Intro.ftz
    CMake Error at /home/demon/programming/git/cosmicos/transform/cmake/convert_js.cmake:9
    (message):
    node returned No such file or directory


    make[2]: *** [transform/COS_Intro.ftz] Error 1
    make[1]: *** [transform/CMakeFiles/assem.dir/all] Error 2
    make: *** [all] Error 2

Maybe we should also add that to the README.md in the troubleshooting section.

Best wishes Johannes

**Comment by aw1231** [comment]
Ok.  Got it.

**Comment by joha2** [comment]
Thank you!

**Comment by paulfitz** [comment]
README updated in #10, thanks @aw1231, thanks @joha2!
